#!/bin/sh

### BEGIN INIT INFO
# Provides:          unicorn
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Manage unicorn server for example
# Description:       Start, stop, restart unicorn server for example.
### END INIT INFO

set -e

USER="example"
NAME="example"
ROOT="/home/$USER/$NAME"
PID="$ROOT/tmp/pids/unicorn.$NAME.pid"
CMD="cd $ROOT; bundle exec unicorn -D -c $ROOT/config/unicorn.rb -E production"
set -u

OLD_PIN="$PID.oldbin"

# Ensure the app exists
cd $ROOT || exit 1

sig () {
  test -s "$PID" && kill -$1 `cat $PID`
}

oldsig () {
  test -s $OLD_PID && kill -$1 `cat $OLD_PID`
}

case $1 in
  start)
    sig 0 && echo >&2 "Already running" && exit 0
    echo "Starting $NAME"
    su - $USER -c "$CMD"
    ;;
  stop)
    echo "Stopping $NAME"
    sig QUIT && exit 0
    echo >&2 "Not running"
    ;;
  force-stop)
    echo "Force stopping $NAME"
    sig TERM && exit 0
    echo >&2 "Not running"
    ;;
  restart|reload|upgrade)
    sig USR2 && echo "reloaded $NAME" && exit 0
    echo >&2 "Couldn't reload, starting '$CMD' instead"
    $CMD
    ;;
  rotate)
    sig USR1 && echo rotated logs OK && exit 0
    echo >&2 "Couldn't rotate logs" && exit 1
    ;;
  *)
    echo >&2 $USAGE
    exit 1
    ;;
esac
